### PR TITLE
only add macros from Defn.h if they are missing

### PR DESCRIPTION
**Pull request by lukasstadler**
this fix the issue raised in #248

### CODE REVIEW

**Comment by lukasstadler** [comment]
looks like a problem with the travis r support - I filed https://github.com/travis-ci/travis-ci/issues/7370

**Comment by gagolews** [comment]
Waiting for the issue to be resolved then.

**Comment by gagolews** [comment]
OK, I fixed the corresponding issue myself - each macro has its own `#ifndef now`, which I prefer more.

**Comment by lukasstadler** [comment]
thanks a lot!
I was waiting for the travis/r issues to be resolved, but that seems to take longer than expected.

**Comment by gagolews** [comment]
Cool! Good luck with `fastr`, I played with it for a little while, looks very promising.

**Pull request closed without merging**
