### PR TITLE
"omit_na=TRUE" keeps the string as is if the replacement is NA

### LINKED ISSUE #267: Can stri_sub<- keep the string as is if the replacement is NA?
In base R, we sometimes find the combination of `regexpr` and `regmathces<-` useful to partially replace strings after some processing. Since `regmatches<-` do nothing when the index is `-1`, which means no match, we can use it without considering if there are any elements that are not matched. Here is an example:

```r
text <- c("A1", "B1", "CC")
pattern <- "[A-Z][0-9]"

m <- regexpr(pattern, text)
m
#> [1]  1  1 -1
#> attr(,"match.length")
#> [1]  2  2 -1
#> attr(,"useBytes")
#> [1] TRUE

regmatches(text, m) <- sapply(regmatches(text, m), tolower)
text
#> [1] "a1" "b1" "CC"
```

I wonder if I can do similar things with stringi, using `stri_locate` and `stri_sub<-`. But, `stri_sub<-` replaces the original string with `NA` if the replacement for the element is `NA`.

``` r
library(stringi)

text <- c("A1", "B1", "CC")
pattern <- "[A-Z][0-9]"

m <- stri_locate(text, regex = pattern)
m
#>      start end
#> [1,]     1   2
#> [2,]     1   2
#> [3,]    NA  NA

stri_sub(text, m)
#> [1] "A1" "B1" NA

stri_sub(text, m) <- sapply(stri_sub(text, m), tolower)
text
#> [1] "a1" "b1" NA
```

`omit_na = TRUE` works when the `from` or `to` is `NA`, but it has no effect if the replacement is `NA`

```r
text <- c("A1", "B1", "CC")

# the original string is saved if from is NA
stri_sub(text, from = c(2,2,NA), omit_na=TRUE) <- "0"
text
#> [1] "A0" "B0" "CC"

# all elements are replaced with NA
stri_sub(text, from = c(2,2,NA), omit_na=TRUE) <- NA
text
#> [1] NA NA NA
```

I feel it is better to ignore replacements with `NA` when `omit_na = TRUE`. Do you have any idea?

### PR DESCRIPTION
**Pull request by yutannihilation**
Fixes #267.

### CODE REVIEW

**Comment by gagolews** [comment]
Cool. Can you update documentation in `R/sub.R` too?

```
@param omit_na single logical value; if \code{TRUE}, missing values in \code{from},
#' \code{to}, or \code{length} will result in an unchanged input; replacement function only
```

should rather now be "....missing values in any of the arguments provided will result..."

**Comment by yutannihilation** [comment]
Thanks! I did updae.

Really thanks for your suggestion of the paragraph, as I'm not so good at English 👍

**Comment by yutannihilation** [comment]
By the way, why is the CI falling with `STRINGI_DISABLE_ICU_BUNDLE="1"`? The error says below. Is this up to my PR?

```
checking with pkg-config for the system ICU4C... no
*** pkg-config did not detect ICU4C-devel libraries installed
*** Trying with "standard" fallback flags
checking whether we may build an ICU4C-based project... yes
checking programmatically for sufficient U_ICU_VERSION_MAJOR_NUM... no
*** The available ICU4C cannot be used
*** Failed to configure package build with forced system ICU usage
*** Consider installing, e.g., libicu-devel (RHEL, Fedora) or libicu-dev (Debian, Ubuntu)
*** together with pkg-config
ERROR: configuration failed for package ‘stringi’
* removing ‘/home/travis/build/gagolews/stringi/stringi.Rcheck/stringi’
```

**Comment by gagolews** [comment]
Thanks! Don't worry about the failing travis CI checks, it seems like I have to upgrade the build settings.

**Comment by yutannihilation** [comment]
Oh, I see. Thanks for merging!

**Pull request merged**
