### PR TITLE
%S+% and other 'Safe' concatenation and comparison operators

### PR DESCRIPTION
**Pull request by AndreMikulec**
From issue
#281 

I created the safe operators.
```
  '%S!=%' '%S!==%' '%S+%' '%S<%' '%S<=%' '%S==%' '%S===%' '%S>%'
  '%S>=%
```
I minimally documented them.

I am on windows.  I could not do a configure ( or know how).

```
Warning: file 'stringi/cleanup' did not have execute permissions: corrected
Warning: file 'stringi/configure' did not have execute permissions: corrected
```
Maybe because of this.
```r
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
 ICU init failed: U_FILE_ACCESS_ERROR 
```
The pull does include some simple testhat tests ( 3 of them ) 
and examples that are the same as the testthat tests.

I could build the documentation.
```r
> roxygen2::roxygenize('.', roclets=c('rd', 'collate', 'namespace'))
Loading required package: tools
Writing oper_comparison.Rd
Writing oper_plus.Rd
Writing stri_list2matrix.Rd
Writing Safe.Rd
Writing NAMESPACE
```

### CODE REVIEW

**Comment by AndreMikulec** [comment]
I see the failed Travis build.

```
Missing link or links in documentation object 'stri_list2matrix.Rd':
  ‘Safe’
```

I have 'no idea' where to put my function called 'Safe'.

I used it within code in both files: join.R and compare.R

I put in here because it makes sense.
```
utils.R
```
I no 'nearly' nothing about rdoxygen.
I just followed the pattern I saw with my eyes.

Please, decide yourself where to put the function called 'Safe. (and its documentation) '

**Comment by gagolews** [comment]
I will give it a look next week (currently very busy with my research activities)

**Comment by AndreMikulec** [comment]
Marek Gagolewski,

Any conclusion?

**Comment by gagolews** [comment]
Hi, apologies, a new academic year just started, I'm extremely busy. But I remember about the pull request and I'll get back to it as soon as I have more time. Stay tuned

**Pull request closed without merging**
